Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.password = "vagrant"
  config.ssh.username = "vagrant"
  config.vm.network "forwarded_port", guest: 22, host: 22
  config.vm.network :private_network, ip: "192.168.44.44"
  config.ssh.forward_agent = true
end
