version: '3'
services:
  infracheck:
    container_name: infra-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
  backend:
    container_name: infra-backend
    build:
      context: ./backend
      dockerfile: build/Dockerfile
