version: '3'
services:
  frontend:
    container_name: infra-frontend
    build:
      context: ./frontend
      dockerfile: build/Dockerfile
    environment:
      SECURE: 'true'          # 'true': use 'nuxt auth' module and display proper login page
  backend:
    container_name: infra-backend
    environment:
      SECURE: 'true'          # 'true': API requires authentication before use
      PASSWORD: 'secret'      # Password for the api authentication
    build:
      context: ./backend
      dockerfile: build/Dockerfile
  reverse:
    container_name: infra-reverse
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
