version: 2
jobs:
  build:
    working_directory: ~/backend
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install requirements
          command: cd backend && pip install -r requirements.txt
  test:
    working_directory: ~/backend
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run backend uittests
          command: cd backend && python -m unittest discover -s test -v
