version: 2
jobs:
  build:
    working_directory: ~/backend
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: pip install -r backend/requirements.txt
      - run: |
          cd backend
          python -m unittest discover -s test
