version: 2.1
workflows:
  version: 2
  build-test:
    jobs:
      - test
jobs:
  test:
    working_directory: ~/backend
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install build requirements
          command: cd backend && pip install -r requirements/build.txt
      - run:                                                                                                                                                                                                                         
          name: Install test requirements                                                                                                                                                                                           
          command: cd backend && pip install -r requirements/test.txt      
      - run:
          name: Run backend uittests
          command: cd backend && python -m unittest discover -s test -v
