version: 2
jobs:
  build:
    working_directory: ~/backend
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |  # use pipenv to install dependencies
            pip install -r requirements.txt
