Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end
  config.vm.box = "mwrock/Windows2016"
  config.vm.hostname = "host-win"
  winClientIP = "192.168.200.200"
  config.vm.network "private_network", ip: winClientIP
  config.vm.communicator = "winrm"
  config.winrm.password="vagrant"
  config.winrm.username="vagrant"
end
